### ISSUE TITLE
Get strange results using the pre-trained model

### ISSUE THREAD

**Issue by zhiqizhang** [amirbar/speech2gesture#11]
Thank you very much for publish this excellent work. I am trying the inference code with your provided pre-trained model. I downloaded some audio from ellen show, and use these audio as the model input audio. But the pose generated looks not right, especially for the hands. I wonder if I messed something up. or I need to do some preprocess for the audio I downloaded from web. 
Another question is what I will get if I take somebody else's audio as input of Ellen's model? Will I still get reasonable results?  

Thank you very much!

**Comment by shinydinosaur** [comment]
Ellen's hand detections using OpenPose are very noisy, which is probably the problem you are experiencing. We try to fix this in a follow-up paper: http://people.eecs.berkeley.edu/~evonne_ng/projects/body2hands/ The code for this will be released soon. In the meantime, we propose to use one of the people with cleaner hand detections, such as John Oliver or Conan.

You should get reasonable results when you transfer audio from one person to another. It's just a bit meaningless as a thing to do (people are different, they say different things, and they say them differently).
