### ISSUE TITLE
where is the frame_df.csv.tgz

### ISSUE THREAD

**Issue by evelynyhc** [amirbar/speech2gesture#13]
hello, appricate your work! 
have a question, where is the frame_df.csv.tgz? I cannot find it in the link, please tell me how and where to get it , thanks.

**Comment by shinydinosaur** [comment]
Try this https://drive.google.com/file/d/1IlrtaJlZXq0ZhbSJ49t3lndlQ01bszE4/view?usp=sharing

**Comment by evelynyhc** [comment]
> Try this https://drive.google.com/file/d/1IlrtaJlZXq0ZhbSJ49t3lndlQ01bszE4/view?usp=sharing

ok, thanks for your reply, I will try it soon
