### ISSUE TITLE
about gan

### ISSUE THREAD

**Issue by evelynyhc** [amirbar/speech2gesture#14]
hello, appricate your work!
have a question, after try your pretrained models, the result is some  skeletal animation，but i want to get some animation with human action, did i do something wrong? if i did wrong, pleace help me which file should i run,  thanks.

**Comment by shinydinosaur** [comment]
Do you mean you want video output? For that, you would need to use something like this https://github.com/carolineec/EverybodyDanceNow to go from wireframe motion to video!

**Comment by evelynyhc** [comment]
> 您是说要视频输出吗？为此，您需要使用类似[https://github.com/carolineec/EverybodyDanceNow的](https://github.com/carolineec/EverybodyDanceNow)东西来将线框运动转换为视频！

ok, i will try ,thanks!
