### ISSUE TITLE
Random noise in Generator

### ISSUE THREAD

**Issue by yzhou359** [amirbar/speech2gesture#2]
Hello Amir, 

Does your generator provide any random noise as input? or it generates the same pose based on the same audio input? I'm working on a similar sequence generation project. I'm curious how you put the randomness into sequence. 

Thanks.

**Comment by amirbar** [comment]
In the current implementation we do not condition on any randomness. However, I believe it may be useful in future work, as for any particular speech sequence we believe there could be few possible gestures.
