### ISSUE TITLE
Insufficient driver version: 410.79.0

### ISSUE THREAD

**Issue by deepconsc** [amirbar/speech2gesture#3]
Hi!

I've tried to run the inference on ellen's checkpoint by installing CUDA 9.0 on Google Colab, and running the command 
```!python -m audio_to_multiple_pose_gan.predict_audio --audio_path speech.wav --output_path output --checkpoint checkpoint/ckpt-step-296700.ckp --speaker ellen -ag audio_to_pose_gans --gans 1```

It throws the following error:

```2019-08-06 01:49:17.499788: E tensorflow/stream_executor/cuda/cuda_dnn.cc:332] could not create cudnn handle: CUDNN_STATUS_NOT_INITIALIZED```
```2019-08-06 01:49:17.499934: E tensorflow/stream_executor/cuda/cuda_dnn.cc:340] possibly insufficient driver version: 410.79.0```

**Comment by deepconsc** [comment]
Well, installing CUDnn manually helped. 
And, in case you're using Google Colab, here's instructions for it:

1. Uninstall CUDA 

```
!apt-get --purge remove cuda nvidia* libnvidia-*
!dpkg -l | grep cuda- | awk '{print $2}' | xargs -n1 dpkg --purge
!apt-get remove cuda-*
!apt autoremove
!apt-get update
```

1. Execute the following code for CUDA installation

```
!wget http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/cuda-repo-ubuntu1604_9.0.176-1_amd64.deb
!wget http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1604/x86_64/libcudnn7_7.0.5.15-1+cuda9.0_amd64.deb
!wget http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1604/x86_64/libcudnn7-dev_7.0.5.15-1+cuda9.0_amd64.deb
!wget http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1604/x86_64/libnccl2_2.1.4-1+cuda9.0_amd64.deb
!wget http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1604/x86_64/libnccl-dev_2.1.4-1+cuda9.0_amd64.deb
!sudo dpkg -i cuda-repo-ubuntu1604_9.0.176-1_amd64.deb
!sudo dpkg -i libcudnn7_7.0.5.15-1+cuda9.0_amd64.deb
!sudo dpkg -i libcudnn7-dev_7.0.5.15-1+cuda9.0_amd64.deb
!sudo dpkg -i libnccl2_2.1.4-1+cuda9.0_amd64.deb
!sudo dpkg -i libnccl-dev_2.1.4-1+cuda9.0_amd64.deb
!sudo apt-get update
!sudo apt-get install cuda=9.0.176-1
!sudo apt-get install libcudnn7-dev
!sudo apt-get install libnccl-dev

!export PATH=/usr/local/cuda-9.0/bin${PATH:+:${PATH}}
!export LD_LIBRARY_PATH=/usr/local/cuda-9.0/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
```


2. Manually download cuDNN v7.6.2 (July 22, 2019), for CUDA 9.0 from NVIDIA website
(You'll be required to sign in/up)
```
https://developer.nvidia.com/rdp/cudnn-download
``` 
And install it using the instructions given by NVIDIA.

**Comment by amirbar** [comment]
Thanks! I must have forgot to include cuDNN as a dependency.

**Comment by deepconsc** [comment]
You're welcome!
