### ISSUE TITLE
Output is only predicted pose plots

### ISSUE THREAD

**Issue by deepconsc** [amirbar/speech2gesture#4]
After running inference, the output is only predicted pose plots, not synthesized video. 

<img width="1680" alt="Screen Shot 2019-08-06 at 06 13 56" src="https://user-images.githubusercontent.com/48494620/62506369-6762e500-b811-11e9-94db-1d2516acd864.png">

**Comment by amirbar** [comment]
Hi @deepconsc,

Synthesizing videos was not a major part of this work and was a focus of different work (https://carolineec.github.io/everybody_dance_now/).

I think there should be some open source implementations of that:
https://github.com/search?o=desc&q=everybody+dance+now&s=stars&type=Repositories

**Comment by deepconsc** [comment]
Totally understand. Me and my team are doing some research for end2end speech to sign language conversion/generation. This is huge inspiration.
You and your team are doing really creative work, with creative approach. Thank you for the work!

**Comment by amirbar** [comment]
Thanks
:)
