### ISSUE TITLE
A few typos & missed instructions in dataset.md

### ISSUE THREAD

**Issue by zeyuanchen23** [amirbar/speech2gesture#5]
This is a great project! I found a few typos / missed instructions while following the [dataset.md](https://github.com/amirbar/speech2gesture/blob/master/data/dataset.md) page to prepare the dataset. Hope this could be helpful to other people.

Typos:
1. Folder structure in **_Download speaker data / 4 Download the speaker videos from youtube._**. There should be one video folder for each speaker instead of two

2. Download **crop_intervals.py** rather than **crop_intervals.csv**

Missed Instructions

1. _youtube_dl_ is used in download_youtube.py, but it is not in the requirements.txt. To solve this:
`pip install --upgrade youtube_dl
`

**Comment by amirbar** [comment]
fixed , thanks.
