### ISSUE TITLE
Enhancement - Gesture 2 Speech 

### ISSUE THREAD

**Issue by PrinceP** [amirbar/speech2gesture#7]
Hi @amirbar,
Can the dataset be helpful in the generation of speech using gestures?
Sign language applications, human-computer interaction can be some of the applications.

**Comment by amirbar** [comment]
Yes, sounds like an interesting trajectory. You can definitely try to modify the code to do the reverse task.

**Comment by OWLonoak** [comment]
Actually,most of gesture are in rest position.Also,different from sign language, the pattern of special person shown frequently.So, I think it’s hard to&nbsp;directly&nbsp;generate speech from gesture .


------------------ Original ------------------
