### ISSUE TITLE
How can you run your network on arbitrary audio durations at test time?

### ISSUE THREAD

**Issue by WinstonDeng** [amirbar/speech2gesture#8]
> "During training, we take as input spectrograms corresponding to about 4 seconds of audio and predict 64 pose vectors, which correspond to about 4 seconds at a 15Hz frame-rate. At test time we can run our network on arbitrary audio durations"(Section 4.3).

What are the details of the testing implementation?

**Comment by amirbar** [comment]
>How can you run your network on arbitrary audio durations at test time?

To do this, we input the audio as is (+padding) and then resize a hidden layer such that it matches the required pose sequence length shape.

For more details, please refer to the test script of our code, which is compatible with arbitrary audio length:
https://github.com/amirbar/speech2gesture/blob/master/audio_to_multiple_pose_gan/predict_audio.py

**Comment by WinstonDeng** [comment]
Thanks for your reply!
